travis:
  secure:
    BINSTAR_TOKEN: lZWHg6hHvTnRet4SpjX/bLIiUSL1JmggBUq4OONZMgxLBQPtAeq8DN+DKBHDH9pG9VB9tYEQdLJeEXzK29Va5fGeTlmpyUb54P1wVYkbmqrYohTsknzJUSv6baPbpBDiwMAEmyxc6TOeABp2Xqxhwdowe1136PZMdv5p7zmDKxK6aRPx/6Fim8DrvHmZd56uvaU+ZgFy7dqguHy4+mzS2x5AXTJL00Kld6v0JVoYrRMoukVskpr6HpdH2CJGhScDfwDPzJ+7alMmCL1R8AEObMMbuzKrNnIWfq2pHg0Ul+639WUeMrYhRsGykc6Y1gHqk68Ra2do2A302FUWYXlWnMaNI2FU4GAxtc8z24STnt4VYt51OAie8l8l0FJFmAQ+F1pen1/gmuXyDk88QgqNwfgIIZ0t8GjHHJkbOliSLP4GC2+WBxrlPsOstjCAjmQWUqJRRFjxoWvKnUjjSczXJfBmI3pPsQ6XfCvw1bx2Y4HeY45ugiJ6E7odXiG4zDIizR2oMYxPC+2saQF2jy2/JuQye+aqKNGcgxa03EAMPCnw9fHuxg0Evp4Dc3NKKQA75c4YVT2wBTl6Yg+IRZvpvYsIxFdtZnuJub0UxITV+GuZKHiZ2ekqgpDHtZgLBl6/OYZ9f5v6Os68endSeGB9XgRZmnJtePFiuyNfy/G5aAA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
