travis:
  secure:
    BINSTAR_TOKEN: F9pL2xoFYkdbAgjOr4zxTfsYlTZQk3NNPi2wesv4zOI95x7yKIB8GmcXuQ0knU76TyYMi4ptwlvck0ANpzMl7nF+FlHV6LGafgLAFE0LgDSEu0QAlxI2QEJsLPO9Jcw9nQ229Q9aNeTcTYEVE5BOrn9y8S9aG5amOOlcZA/rthB78zkjvlGAL+1lu8W/YS11SLA6fd/1cmHtmTKmSADBr57iXRRUd90BW9g6Yq9S8ToOL87imYtbyYh51WJjSmA6sID/8JqxD2Bz1wI9cipmMnJFwJ3cD1sC1wZplH/7jQNzzcxwjKI9xz2GiJb5gdcL9i40sQeRCcQOk/5XQBYgZbJAzsO+NmyxT28ikHD128gD0P7EXNlRYOjC+rzVx20cq1bvG7GfdRDGLtu7GPEwNKBjYv+o+VCNw1BZFJ5cf1A7ZIzfleBDQpF529WCTFtF8kv3OwKMWcKWPje5GLborf8CKSETzm76WTaII4ExaAEyzXuQS/qv/uzjP1z84ZZ108pjorRQKSt2dXNvZHaD3rc/ed3NwTg2l/H5TI1ueVoIAKFHp2hc4b/ouxL504OvCh6sYdqg6gc5+yHTj39QzsWYm+ivod0gSldgEH8S6r6jUhfR1rwl+BAf2WH27Z6QTu6Hiqi81uLZMYwFWbGIpn8TMpxvukCHeoZa9aX49VE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
